const main = require("./mainFunction");
main().catch((e) => {
  console.error(e);
});
