const main = require("mainFonction");

main().catch((e) => {
  console.error(e);
});
